// <auto-generated />
using System;
using DoctorScheduling.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoctorScheduling.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314081808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoctorScheduling.Models.Domain.Entities.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Email")
                        .IsUnique();

                    b.ToTable("Attendees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "s.mitchell@practice.nhs.uk",
                            EventId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "Dr Sarah Mitchell",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "j.okafor@practice.nhs.uk",
                            EventId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "Nurse James Okafor",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "s.mitchell@practice.nhs.uk",
                            EventId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Name = "Dr Sarah Mitchell",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "p.sharma@practice.nhs.uk",
                            EventId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Name = "Dr Priya Sharma",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "j.okafor@practice.nhs.uk",
                            EventId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Name = "Nurse James Okafor",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "l.chen@practice.nhs.uk",
                            EventId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Name = "Reception Manager Lisa Chen",
                            Status = 1
                        });
                });

            modelBuilder.Entity("DoctorScheduling.Models.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsCancelled");

                    b.HasIndex("StartTime", "EndTime");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Daily briefing to review patient schedules, flag complex cases, and coordinate care across the practice.",
                            EndTime = new DateTime(2026, 3, 16, 9, 30, 0, 0, DateTimeKind.Utc),
                            IsCancelled = false,
                            Location = "Staff Room",
                            RowVersion = 0L,
                            StartTime = new DateTime(2026, 3, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Clinical Huddle"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Review of clinical audit results, significant events, and practice performance against QOF targets.",
                            EndTime = new DateTime(2026, 3, 17, 15, 30, 0, 0, DateTimeKind.Utc),
                            IsCancelled = false,
                            Location = "Practice Meeting Room",
                            RowVersion = 0L,
                            StartTime = new DateTime(2026, 3, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Quarterly Clinical Governance Review"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly all-staff meeting covering operational updates, policy changes, and flu vaccination clinic planning.",
                            EndTime = new DateTime(2026, 3, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCancelled = false,
                            Location = "Main Reception Area",
                            RowVersion = 0L,
                            StartTime = new DateTime(2026, 3, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Practice Staff Meeting"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            CancellationReason = "Vendor delayed system deployment",
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hands-on training session for the new online patient booking and triage system.",
                            EndTime = new DateTime(2026, 3, 18, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCancelled = true,
                            Location = "IT Suite",
                            RowVersion = 0L,
                            StartTime = new DateTime(2026, 3, 18, 13, 0, 0, 0, DateTimeKind.Utc),
                            Title = "New Patient Portal Training"
                        });
                });

            modelBuilder.Entity("DoctorScheduling.Models.Domain.Entities.Attendee", b =>
                {
                    b.HasOne("DoctorScheduling.Models.Domain.Entities.Event", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DoctorScheduling.Models.Domain.Entities.Event", b =>
                {
                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
